{
    "name": "Purchase Request",
    'author': 'SMARTEST - ALGERIA',
    "version": "1.0.0",
    "summary": "Use this module to have notification of requirements of "
    "materials and/or external services and keep track of such "
    "requirements.",
    "category": "Purchase Management",
    "depends": [
        "purchase",
        "smartest_base",
        'hr',
        # 'website',
        'account',
        'smartest_l10n_dz'
    ],
    "data": [
        "security/purchase_request.xml",
        "security/purchase_validator.xml",
        "security/ir.model.access.csv",
        "data/purchase_request_sequence.xml",
        "data/purchase_request_data.xml",
        "reports/report_purchase_request.xml",
        "views/purchase_request_view.xml",
        "views/purchase_request_line_view.xml",
        "views/purchase_request_report.xml",
        "views/purchase_order_view.xml",
        "data/request_approval_email.xml",
        "views/purchase_validator.xml",
        # "views/portal_template.xml",
        "views/product_template.xml",
        "views/account_move.xml",
        "views/stock_picking.xml",
        "views/res_groups.xml",
        "reports/report_purchase_order.xml",
        "reports/demande_reglement.xml",
        "reports/service_done.xml",
    ],
    "demo": ["demo/purchase_request_demo.xml"],
    "installable": True,
    "application": False,
    'license': 'LGPL-3',
}
