from . import hr_employee
from . import hr_leave
from . import hr_leave_type
from . import hr_leave_accrual
from . import hr_leave_allocation
from . import res_company
from . import res_config_settings
from . import range_days
from . import hr_contract
from . import resource_calendar
from . import leave_categories
